### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by PhanaticD** [macjuul/CHBossBars#1]
new release so i can be lazy and not have to compile? :D

**Comment by macjuul** [comment]
Sure, I'll write a documentation as well

**Comment by macjuul** [comment]
Here you go
https://github.com/macjuul/CHBossBars/releases/tag/v1.0.0.1

**Comment by macjuul** [comment]
Completed the documentation, I hope it'll help you. Thank's for using my extension :)

**Comment by PhanaticD** [comment]
thanks!
